name: "CI (Integração Continua): Main Workflow"

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Installation
        run: yarn install
      - name: Run Linter
        run: yarn lint
      - name: Run Build
        run: yarn build
        
  test_e2e:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16.13.0
          cache: 'yarn'
      - name: Cypress
        uses: cypress-io/github-action@v6
        with: 
          browser: edge
          
